### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by grinapo** [TenGbps/ISX_BL#1]
Hello,

It's not trivial to contact you, and maybe this issue have a smaller impact than tweeting you. ;)

Anyway. There seems to be a discrepancy between dnsbl.isx.fr DNS zone and the list available on the website; at least one IP is not listed in the raw list but DNS answers 127.0.0.2; in my case it's 8.208.147.91.dnsbl.isx.fr. 

You may want to look into it. And maybe provide a private way to contact you, just in case. *hint* ;-)

**Comment by TenGbps** [comment]
The raw list only contant the last 15 days active ips for not overload firewall list set.

Only manual action can unlist ip form RBL.

Thanks you !

**Comment by grinapo** [comment]
You should possibly document that here and elsewhere. It is pretty weird when someone wants to check it.

**Comment by TenGbps** [comment]
Update ! You can remove by your self on https://bl.isx.fr/

**Comment by grinapo** [comment]
I'm honoured. Thanks! :-) Merci! ;-)
