### ISSUE TITLE
Delist process broken

### ISSUE THREAD

**Issue by Peneheals** [TenGbps/ISX_BL#4]
I'm opening this issue, because "the address [business@isx.fr] couldn't be found or is unable to receive email".

I've found a bug in your blacklist delist process: if I want to delist an IP and arrive to https://bl.isx.fr/allow.php after I entered the blacklisted item, it tells me to do so:

_curl -s https://bl.isx.fr/allow.php?ipaddress=XX.XX.XX.XX&hash=XXXc2354decbd339219ee47f2d190050aca6bXXX&source=XX.XX.XX.XX_

Because this url contains an "&" sign, the curl command breaks at half way. You should put the whole url into double quotes and assume to run that, like this:

_curl -s "https://bl.isx.fr/allow.php?ipaddress=XX.XX.XX.XX&hash=XXXc2354decbd339219ee47f2d190050aca6bXXX&source=XX.XX.XX.XX"_

And because of that "-s", the user won't get any useful information. You should remove that too.

**Comment by TenGbps** [comment]
Thanks you @Peneheals, is now fixed
