### ISSUE TITLE
Delist process didn't work

### ISSUE THREAD

**Issue by moritzfriedrich** [TenGbps/ISX_BL#5]
The sent Delist-Form explains to me to access the page from the listed IP. But if I call the same URL via CURL I get the following output, 
> root@s025 [~]$ curl https://bl.isx.fr/allow.php?ipaddress=XXX.XXX.X.XX&otp=&allowbut=Allow+this+ip&token=03ADlfD.*ReijEl1054fBg
> [1] 3893094
> [2] 3893095
> [3] 3893096
> [2]-  Done                    otp=
> [3]+  Done                    allowbut=Allow+this+ip

however, the IP is still on the blacklist.
Is there something missing?

**Comment by moritzfriedrich** [comment]
The delisting process still dosn't work for me. Do you have any hint?

**Comment by r41n403** [comment]
I am having the same issue and I have multiple IPs listed, any way you could provide some documentation if using curl won't work?

**Comment by r41n403** [comment]
> I am having the same issue and I have multiple IPs listed, any way you could provide some documentation if using curl won't work?

I reached out through twitter and was able to get my ips delisted. Thanks.

**Comment by Cicco0** [comment]
@awooapache 
There is a workaround for this:

1. Install tinyproxy on your server:
`yum install -y tinyproxy && systemctl start tinyproxy`

2. Connect from your computer to your server:
`ssh -L 8888:127.0.0.1:8888 <server-ip> -N`

3. Use proxy-settings in firefox:
Firefox => Connection Settions => Manual proxy configuration => 127.0.0.1 Port: 8888 and set mark to «Use this proxy server for all protocols»

4. Browse to the site bl.isx.fr and unlist your server

**Comment by TenGbps** [comment]
Use OTP : 123456
